---
- hosts: localhost
  collections:
    - netapp.ontap
  vars:
    login: &login
      username: "{{ ontap_user }}"
      password: "{{ ontap_password }}"
      hostname: "{{ ontap_api_interface }}"
      https: true
      validate_certs: false
  tasks:
    - name: config IPSec for ONTAP
      na_ontap_command:
        command: ['security', 'ipsec', 'config', 'config', '-is-enabled', 'true']
        <<: *login
    - name: config IPSec policy for ONTAP
      na_ontap_command:
        command: ['security', 'ipsec', 'policy', 'create', '-vserver', 'svm_gketest', '-name', 'ipsec_test', '-local-ip-Subnets', '"{{ ipsec_target_cidr }}"', '-remote-ip-subnets', '"{{ ipsec_source_cidr }}"', '-shared-key', '"{{ ipsec_secret }}"']
        <<: *login
- hosts: ipsec
  tasks:
    - name: install IPSec on servers
      include_role:
        name: ipsec-config
