---
# tasks file for ipsec-config
- name: "ipsec-config | Install Packages"
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - strongswan
      - charon-systemd
      - strongswan-swanctl
  when: ansible_os_family == 'Debian'
  become: true

- name: "ipsec-config | Copy swanctl.conf template"
  template:
    src: swanctl.conf.j2
    dest: /etc/swanctl/swanctl.conf
  become: true

- name: "ipsec-config | Reload swanctl config"
  shell:
    cmd: swanctl --load-all
  become: true




